bannedUsers = []
debugginMode = False
botOwner = "bruno_xc"
muteStatus = False
imgsDir = "imgs"
maxFileSize = 10 * 10**6 # 10MB
newImagePrefix = "imagenCargadaPorBot-"
newImageSufix = ".jpg"
newImageIndexPath = "new_image_index"