DEFAULT_LANG = 'es'
bannedUsers = []
debugginMode = False
BOT_OWNER = 6390834871
muteStatus = False
IMGS_DIR = "../imgs"
MAX_FILE_SIZE = 10 * 10**6 # 10MB
NEW_IMG_PREFIX = "imagenCargadaPorBot-"
NEW_IMG_SUFIX = ".jpg"
NEW_IMG_INDEX_PATH = "new_image_index"